---
# Simple example - just remove obsolete kernels
- name: Remove obsolete kernels
  hosts: all
  become: yes
  tasks:
    # noqa syntax-check[unknown-module]
    - name: Clean up old kernels
      kernsweep:
        state: absent
